language: php

php:
- 7.1
- 7.2
- 7.3

notifications:
  email:
  - team@appwrite.io

services:
- docker

before_install:
- docker-compose up -d

before_script: composer install

script:
- vendor/bin/phpunit --configuration phpunit.xml