language: php

php:
- 7.1
- 7.2
- 7.3

notifications:
  email:
  - team@appwrite.io

before_install:
- sudo apt-get update
- sudo apt-get install -y clamav clamav-daemon wget
- wget -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd
- wget -O /var/lib/clamav/daily.cvd http://database.clamav.net/daily.cvd
- wget -O /var/lib/clamav/bytecode.cvd http://database.clamav.net/bytecode.cvd
- chown clamav:clamav /var/lib/clamav/*.cvd
- sudo clamd

before_script: composer install

script:
- vendor/bin/phpunit --configuration phpunit.xml