language: php

php:
- 7.1
- 7.2
- 7.3

notifications:
  email:
  - team@appwrite.io

before_install:
- sudo apt-get update
- sudo apt-get install -y clamav clamav-daemon
- sudo clamd

before_script: composer install

script:
- vendor/bin/phpunit --configuration phpunit.xml